### ISSUE TITLE
.git and .github appears when using FOLDER: '.'

### ISSUE THREAD

**Issue by antocuni** [jayanta525/github-pages-directory-listing#16]
As the title says, here is my workflow:
https://github.com/antocuni/files2/blob/main/.github/workflows/workflow.yml

```
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: '.'
```

And here is the result:
https://antocuni.github.io/files2/

![Image](https://github.com/user-attachments/assets/416ed521-a3ef-4432-acf6-a0246030e4dd)
